Repository SoPra-Team-10/GameLogic, pull requests merged in 2019-05, with the labels that each got.

#49 Fixed #43
  Action.cpp
Labels: enhancement

#84 getBallByID() impl. -> fixed #83 issue
  GameModel.cpp
  GameModel.h
Labels: feature requeset

#88 Quaffel Entreißen Action -> fixed #78
  Action.cpp
  Action.h
  Tests/Interferences.cpp
  Tests/SopraGameAction.cpp
  Tests/SopraGameController.cpp
Labels: todo

#113 Feature/quaffel reset
  GameController.cpp
  GameController.h
  GameModel.h
  Tests/SopraGameController.cpp
Labels: todo

#123 fixed #118 (ban check überall ergänzen)
  Action.cpp
  GameController.cpp
  GameModel.cpp
  GameModel.h
  Tests/SopraGameAction.cpp
  Tests/SopraGameModel.cpp
Labels: bug

#130 fixed #126
  GameController.cpp
Labels: bug

#131 fixed #128
  GameController.cpp
Labels: bug

#134 fixed #129
  GameController.cpp
  GameModel.cpp
  GameModel.h
Labels: bug

#156 Snitch wird jetzt tatsächlich gespawnt
  GameController.cpp
  Tests/SopraGameController.cpp
Labels: bug

#161 Sonarcloud integration
  .travis.yml
  CMakeLists.txt
  Dockerfile
  README.md
  run-sonarqube.sh
  sonar-build.sh
  sonar-project.properties
  src/Action.cpp
  src/Action.h
  src/GameController.cpp
  src/GameController.h
  src/GameModel.cpp
  src/GameModel.h
  src/Interference.cpp
  src/Interference.h
Labels: enhancement
